### PR TITLE
Switch to official antlr3 repository

### PR DESCRIPTION
**Pull request by devpow112**

### CODE REVIEW

**Comment by devpow112** [comment]
This doesn't seem to work out of the box. Trying to figure out why

**Comment by devpow112** [comment]
https://github.com/WNProject/WNFramework/pull/162/files#diff-1bcd98a06c6463a4fe320a180109f5c0L31

**Comment by AWoloszyn** [comment]
We had a couple manual changes to this file to get it to compile.

**Comment by devpow112** [comment]
Still working on this. Will make not draft when it's ready

**Comment by devpow112** [comment]
> 😧 something went wrong when rebasing!

We can't rebase draft pull requests.

**Comment by devpow112** [comment]
Abandoning. This won't work with out manual changes to the source files which isn't going to work if it's a submodule. Revisit at some-point if we can do fixes with overlays somehow.

**Pull request closed without merging**
